ci: Introduce lwip test apps
In some cases it's necessary to test more complex scenarios than single
thread unit tests. The initial socket test uses two threads to verify
basic TCP client-server communicaton.

Ref IDF-4797

diff --git a/.github/workflows/ci-linux.yml b/.github/workflows/ci-linux.yml
--- a/.github/workflows/ci-linux.yml
+++ b/.github/workflows/ci-linux.yml
@@ -3,7 +3,7 @@ name: CI
 on: [push, pull_request]
 
 jobs:
-  build:
+  build-and-test:
     strategy:
       matrix:
         compiler: [gcc, clang]
@@ -12,6 +12,7 @@ jobs:
       LSAN_OPTIONS: verbosity=1:log_threads=1
       WGET_PATH: http://download.savannah.nongnu.org/releases/lwip
       CONTRIB: contrib-2.1.0
+      WGET_CHECK2JUNIT_PY: https://raw.githubusercontent.com/gsauthof/utility/42792030/check2junit.py
     runs-on: ubuntu-latest
 
     steps:
@@ -22,6 +23,8 @@ jobs:
         wget --no-verbose ${WGET_PATH}/${CONTRIB}.zip
         unzip -oq ${CONTRIB}.zip
         patch -s -p0 < test/${CONTRIB}.patch
+        python -m pip install lxml junit-xml
+        wget --no-verbose ${WGET_CHECK2JUNIT_PY}
 
     - name: Build and Run unit tests with make
       run: |
@@ -55,6 +58,50 @@ jobs:
 
     - name: Build and run unit tests with cmake
       run: |
+        export LWIP_DIR=`pwd`
         cd ${CONTRIB}/ports/unix/check
         mkdir build && cd build && cmake -DLWIP_DIR=`pwd`/../../../../.. .. -G Ninja
         cmake --build . && ./lwip_unittests
+        python ${LWIP_DIR}/check2junit.py lwip_unittests.xml > ${LWIP_DIR}/unit_tests.xml
+
+    - name: Build and run test apps
+      run: |
+        export LWIP_DIR=`pwd` && export LWIP_CONTRIB_DIR=`pwd`/${CONTRIB}
+        cd test/apps
+        # Prepare a failing report in case we get stuck (check in no-fork mode)
+        python socket_linger_stress_test.py failed > ${LWIP_DIR}/socket_linger_stress_test.xml
+        for cfg in config_no_linger config_linger config_linger_reuse; do
+          cmake -DCI_BUILD=1 -DTEST_CONFIG=${cfg} -B ${cfg} -G Ninja .
+          cmake --build ${cfg}/
+          timeout 10 ./${cfg}/lwip_test_apps
+          python ${LWIP_DIR}/check2junit.py lwip_test_apps.xml > ${LWIP_DIR}/${cfg}.xml
+        done
+        # Run the lingering test multiple times
+        for run in {1..10000}; do ( timeout 10 ./config_linger/lwip_test_apps ) || exit 1 ; done
+        # All good, regenerate the stress test-report, since the test succeeded
+        python socket_linger_stress_test.py > ${LWIP_DIR}/socket_linger_stress_test.xml
+
+    - name: Upload Test Results
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: Test Results ${{ matrix.compiler }}
+        path: "*.xml"
+
+  publish-test-results:
+    name: "Publish Tests Results"
+    needs: build-and-test
+    runs-on: ubuntu-latest
+    permissions:
+      checks: write
+    if: always()
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          path: artifacts
+
+      - name: Publish Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        with:
+          junit_files: "artifacts/**/*.xml"
